//Action names go here

export const FETCH_ALL_POSITIONS = 'FETCH_ALL_POSITIONS';
export const FETCH_EMPLOYERS_POSITIONS = 'FETCH_EMPLOYERS_POSITIONS';

export const FETCH_POSITION = 'FETCH_POSITION';
export const EMPLOYER_ADD_POSITION = 'EMPLOYER_ADD_POSITION';

export const TALENT_REGISTER = 'TALENT_REGISTER';
export const EMPLOYER_REGISTER = 'EMPLOYER_REGISTER';
export const EMPLOYER_LOGIN = "EMPLOYER_LOGIN";
export const TALENT_LOGIN = "TALENT_LOGIN";

export const APPLY_TO_POSITION = "APPLY_TO_POSITION";

export const LOGIN_FAILED = "LOGIN_FAILED";

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';


