//Action names go here

export const FETCH_ALL_POSITIONS = 'FETCH_ALL_POSITIONS';
export const FETCH_POSITION = 'FETCH_POSITION';
export const EMPLOYER_ADD_POSITION = 'EMPLOYER_ADD_POSITION';

export const TALENT_REGISTER = 'TALENT_REGISTER';
export const EMPLOYER_REGISTER = 'EMPLOYER_REGISTER';
export const EMPLOYER_LOGIN = "EMPLOYER_LOGIN";
export const TALENT_LOGIN = "TALENT_LOGIN";
